### PR TITLE
Smaller, more compressed homepage hero image

### LINKED ISSUE #279: Reduce front page weight
The front page is currently about c. 325K.
Over half of this (174K) is the JPEG image (2048x864 at any browser size). Other images are c. 6K, the page is 6.6K, fonts are 50K, JavaScript is c. 65K, CSS 21.5K.
#278 gets the main CSS down to 8.5K and removes 10K of JavaScript, but I think a bit of work on the main image could save the most, on mobile if not everywhere.

### PR DESCRIPTION
**Pull request by zarino**
Down from 174KB to roughly 80KB. Also now includes the photographer’s name, email, and copyright notice, as requested.

Fixes #279.

### CODE REVIEW

**Comment by dracos** [comment]
Could we additionally use srcset or similar so that e.g. a mobile doesn't have to download even a 1400x600 image? Looks like c. 300 in height would be small enough for a standard width phone, which would be more like 30K.

**Comment by zarino** [comment]
Good idea! Stand by…

**Comment by zarino** [comment]
@dracos – Done! Also took the opportunity to tidy up some of `wtt.scss` while I was there.

**Comment by dracos** [comment]
I moved the tidying to a separate commit, as it's a separate thing :)

**Pull request merged**
