### PR TITLE
Increase link contrast and add underline

### LINKED ISSUE #199: User request: better contrast on site
"I got on your website today via an email asking if my MP had responded.

Parts of the text were a pale, pale blue against a white sheet
background.  Unfortunately, this meant eyestrain which led to a
migrane.

On a personal level, I have the Firefox add-on, Stylish, which allows
me to change colours, font sizes, remove un-necessary parts of a page
etc...and I shall be doing this very thing for your website tomorrow.

Unfortunately, not everyone knows about this (and not everyone uses
Firefox).  If pale, pale blue against a white sheet background causes
me problems, it will for others as well.  May I suggest a colour
scheme that is much easier on he eyes, or at least an option of
choosing from, say 3 or 4, for those who have the same difficulty as
myself, as well as for those that are partially sighted and may need,
say, larger text (again, Firefox is the only mainstream browser that
supports "Text Zoom Only", meaning you can enlarge text on a webpage
without having to scroll across."

### PR DESCRIPTION
**Pull request by zarino**
Fixes #199.

I've picked the colours and written the styles by copying css over, piecemeal, into the Chrome dev tools. I can't remember how to get WTT running locally, so I haven't tested this properly.

`#0077a3` is the lightest and bluest we can have a link if we want to maintain AA-level contrast against the page background of `#F4F3EF`.

### CODE REVIEW

**Comment by zarino** [comment]
I've tested this on my vhost. Links are much darker than before, and contrast on light cream backgrounds is now WCAG 2 AA compliant.

Also, links inside paragraphs of text are more obvious now that they have a pale blue underline by default.

@jacksonj04 @mhl – ready to merge if you're happy with it! You'll probably want to squash the four commits into one.

**Comment by jacksonj04** [comment]
I'm happy that it makes us AA compliant on the transactional pages, but we still fail on the help pages (eg https://www.writetothem.com/about-constituency). Not sure what the fix would be other than to make the background lighter.

**Comment by jacksonj04** [comment]
screen shot 2015-01-12 at 11 15 09

**Comment by jacksonj04** [comment]
Oh, wait, mea culpa there. I was looking at the wrong element (`body` still seems to have the old background colour, don't know if that wants tidying up).

**Comment by zarino** [comment]
Lol, you beat me to it. Yes, `#e0dfdb` is the body background (eg: below the homepage footer). The help pages are wrapped in a div with a background of `#F4F3EF`.

**Comment by jacksonj04** [comment]
After double checking my elements, :+1:. You want to squash and merge or should I?

**Comment by zarino** [comment]
@jacksonj04 If you could do it, that would be great.

**Pull request closed without merging**
